name = "ParameterSets"
uuid = "2467ea11-b4b4-4663-8a92-c239b5e084a5"
version = "0.1.0"
authors = ["Sliem el Ela <sliemelela@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
JSON = "1.3.0"
PrettyTables = "3.1.2"
Test = "1"
YAML = "0.4.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
