[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
ParameterSets = "2467ea11-b4b4-4663-8a92-c239b5e084a5"

[sources]
ParameterSets = {path = ".."}
